name: Next.js CI/CD Pipeline

on:
  push:
    branches: 
      - dev
      - main
      - test
  pull_request:
    branches: 
      - main

# Explicitly set permissions for the GITHUB_TOKEN
permissions:
  contents: read
  actions: write
  checks: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install System Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          git \
          curl \
          build-essential \
          libssl-dev \
          ca-certificates
    
    - name: Install Project Dependencies
      run: |
        npm install \
          next \
          react \
          react-dom \
          @types/react
    - name: Install Development Dependencies
      run: |
        npm install -D \
          @testing-library/react \
          @testing-library/jest-dom \
          @testing-library/user-event \
          jest \
          jest-environment-jsdom \
          jest-dom \
          eslint \
          eslint-config-next \
          eslint-plugin-react \
          eslint-plugin-react-hooks \
          prettier \
          @types/jest \
          typescript
    
    - name: Install Additional Utilities
      run: |
        npm install -D \
          cross-env \
          rimraf \
          npm-run-all
    
    - name: Run Linter
      run: |
        npm run lint:check || true
        
    - name: Run Type Checking
      run: npx tsc --noEmit
    
    - name: Run Tests
      run: npm run test -- --coverage
    
    - name: Build Project
      run: npm run build
    
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: nextjs-build
        path: |
          .next
          public
          package.json
          next.config.js
        retention-days: 5
        compression-level: 6
        overwrite: true

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4
      with:
        name: nextjs-build
    
    - name: Deploy to Production
      run: |
        echo "Deploying to production server"
        # Add your deployment script here

  notify:
    needs: [build-and-test, deploy]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Notify Workflow Status
      uses: actions/github-script@v7
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const status = '${{ job.status }}';
          
          console.log(`Workflow status: ${status}`);
          
          // You can add custom notification logic here
          // For example, create an issue or send a message
          if (status === 'failure') {
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Workflow Failed',
              body: `Workflow failed in run ${context.runId}`
            });
          }
